image: ubuntu

before_build:
- sudo apt-get update
- sudo apt-get install -y libsdl2-dev libxml2-dev
- git submodule update --init --recursive

build_script:
- mkdir -p build
- cd build
- cmake -DUSE_LIBTMX=ON ..
- make
- cmake -DUSE_LIBTMX=OFF ..
- make
